version: '3'
services:
  app:
    container_name: go-todo-api
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - fullstack
    environment:
      - DB_HOST=postgres
      - DB_DRIVER=${DB_DRIVER}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - POSTGRES_URL=${POSTGRES_URL}
      # - PORT=${PORT} 

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./docker-compose/postgres:/var/lib/postgresql/data
    networks:
      - fullstack

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
