# DEPLOYMENT SECRET
---
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  labels:
    app: app-name
data:
  .dockerconfigjson: eyAiYXV0aHMiOiB7ICJnaGNyLmlvIjogeyAiYXV0aCI6ImFHRnljMmh6YVc1bmFIWnBPbWRvY0Y5UU1FOHdZbXRXU0VwMVYzbHJObWRPVnpaQ1lWYzRRMFY2Y25sTFVXZ3hkRkp1UlVrPSIgfSB9IH0=

# App Secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  # Postgres Config
  DB_HOST: postgres
  DB_DRIVER: postgres
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_NAME: postgres
  DB_PORT: "5432"
  #Go app PORT configuration
  PORT: "8080"
  POSTGRES_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable # Currently hardcoding DB parameters, could use nested variables as future improvement
  # POSTGRES_URL: postgres://<USER>:<PASS>@<DB-SERVICE-NAME>:5432/simple-service?sslmode=disable # Currently hardcoding DB parameters, could use nested variables as future improvement

# Database secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
